```cpp
throw std::exception("messadge");          //прерывается исполнение как в return)

try {
} catch (const std::exception& e) {        //ловит и всех наследников через виртуальный полиморфизм
	std::cout << e.what(); 
	throw;                             //выбрасывает то же исключение
{
```

Если в конструкторе вылетает исключение, то деструктор не будет инициализирован.
В деструкторе лучше не делать исключений, иначе их может быть несколько и все упадет.

```cpp
int function() noexcept;   (не часть сигнатуры, если функция выдаст исключение, то все упадет)
```
